export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLINIC_ID = "CLINIC_ID";
export const CLIENT_ID = "CLIENT_ID";
export const CLIENT_INSURANCE_ID = "CLIENT_INSURANCE_ID";
export const GET_CLIENT_FLAGS ="GET_CLIENT_FLAGS";
export const SELECTED_CLIENT_ID = "SELECTED_CLIENT_ID";
export const SELECTED_CLIENT_FILTER = "SELECTED_CLIENT_FILTER";

export const REMOVE_CLIENT_FILTER = "REMOVE_CLIENT_FILTER";
export const SELECTED_STAFF_ID = "SELECTED_STAFF_ID";
export const SELECTED_SERVICE_FILTER = "SELECTED_SERVICE_FILTER";
export const GET_STAFF = "GET_STAFF";
export const GET_MARITIALS_STATUS = "GET_MARITIALS_STATUS";
export const GET_GENDER = "GET_GENDER";

export const SELECTED_SERVICE_ID = "SELECTED_SERVICE_ID";
export const STAFF_LOGIN_DETAIL = "STAFF_LOGIN_DETAIL";
export const STAFF_ONLINE_STATUS = "STAFF_ONLINE_STATUS";

export const IMMUNIZATION_ID = "IMMUNIZATION_ID";

export const SELECTED_DRAWER_ROUTE = "SELECTED_DRAWER_ROUTE";
export const SELECTED_HEADER_MENU = "SELECTED_HEADER_MENU";
export const IS_GLOBAL_SEARCH = "IS_GLOBAL_SEARCH";
export const GET_ROLE = "GET_ROLE";
export const GET_CLIENT_DETAILS = "GET_CLIENT_DETAILS";
export const AGE_CAlCULATION = "AGE_CAlCULATION";
export const GET_CLIENT_PROFILE_IMG = "GET_CLIENT_PROFILE_IMG";
export const GET_CLIENT_PROFILE_IMG_BYTES = "GET_CLIENT_PROFILE_IMG_BYTES";
export const GET_STAFF_DETAILS = "GET_STAFF_DETAILS";
export const GET_STAFF_PROFILE_IMG = "GET_STAFF_PROFILE_IMG";
export const GET_CLIENT_INSURANCE = "GET_CLIENT_INSURANCE";
export const USER_CAN_ACCESS = "USER_CAN_ACCESS";
export const GET_PRIMARY_CARE_PHYSICIAN = "GET_PRIMARY_CARE_PHYSICIAN";
export const GET_PEDIATRICIAN = "GET_PEDIATRICIAN";
export const GET_ROLE_PERMISSIONS = "GET_ROLE_PERMISSIONS";

export const DOC_TEMPLATE_INFO = "DOC_TEMPLATE_INFO";

export const SITE_ID = "SITE_ID";
export const ALL_CLIENT_AVAILABLE = "ALL_CLIENT_AVAILABLE";
export const ALL_STAFF_AVAILABLE = "ALL_STAFF_AVAILABLE";
export const SITE_VALUE = "SITE_VALUE";
export const GET_DOCUMENT_FILTER = "GET_DOCUMENT_FILTER";
export const GET_CLINIC_DETAILS_BY_ID = "GET_CLINIC_DETAILS_BY_ID";
